### PR TITLE
Wait with additional langs

### PR DESCRIPTION
**Pull request by stasm**
It turns out there's no value in calling `getAdditionalLanguages` early, before the `interactive` ready state fires.  In fact, it's a bit slower than simply calling it when the service is initialized.  Compare the following Raptor results from the Settings app:

```
Before                            Mean      Median    Min       Max       StdDev  p95     
--------------------------------  --------  --------  --------  --------  ------  --------
coldlaunch.navigationLoaded       860.200   846.500   815.000   962.000   39.242  962.000 
coldlaunch.navigationInteractive  860.300   847.000   815.000   962.000   39.207  962.000 
coldlaunch.contentInteractive     938.700   927.000   892.000   1043.000  40.482  1043.000
coldlaunch.startupPathEnd         2067.400  2066.500  1966.000  2160.000  48.092  2160.000
coldlaunch.visuallyLoaded         2626.100  2611.000  2528.000  2721.000  56.980  2721.000
coldlaunch.fullyLoaded            5217.200  5211.000  5183.000  5295.000  30.099  5295.000
coldlaunch.uss                    16.970    17.000    16.700    17.300    0.173   17.300  
coldlaunch.pss                    20.890    20.900    20.700    21.300    0.181   21.300  
coldlaunch.rss                    35.580    35.550    35.300    36.000    0.199   36.000  
```

```
After                             Mean      Median    Min       Max       StdDev  p95     
--------------------------------  --------  --------  --------  --------  ------  --------
coldlaunch.navigationLoaded       852.000   855.000   814.000   915.000   27.543  915.000 
coldlaunch.navigationInteractive  852.200   855.500   814.000   916.000   27.795  916.000 
coldlaunch.contentInteractive     931.900   937.000   886.000   990.000   28.452  990.000 
coldlaunch.startupPathEnd         2067.400  2079.000  1996.000  2109.000  34.404  2109.000
coldlaunch.visuallyLoaded         2590.000  2582.000  2516.000  2695.000  51.585  2695.000
coldlaunch.fullyLoaded            5211.700  5219.500  5141.000  5265.000  35.154  5265.000
coldlaunch.uss                    16.930    16.900    16.700    17.300    0.190   17.300  
coldlaunch.pss                    20.870    20.800    20.700    21.200    0.168   21.200  
coldlaunch.rss                    35.560    35.500    35.300    35.900    0.180   35.900  
```

This is in line with what @zbraniecki found when we added `getAdditionalLanguages` on master, so let's do it in v3 as well.

### CODE REVIEW

**Comment by stasm** [comment]
Note that I based this PR on top of #34, but it's not a hard requirement.  It was just easier to do.

**Comment by stasm** [comment]
The beef is at https://github.com/stasm/l20n.js/commit/45c6b70a91bb0b6fde4a43a64f2cd193139650e8.

**Comment by stasm** [comment]
Unfortunately, I'm getting `TypeError: navigator.mozL10n is undefined` when Settings launch so I'm not sure how reliable are the results above.  I'll check with FM radio later today.

**Comment by stasm** [comment]
Here are the results for FM Radio:

```
Before                            Mean     Median   Min      Max      StdDev  p95    
--------------------------------  -------  -------  -------  -------  ------  -------
coldlaunch.navigationLoaded       368.300  346.500  313.000  504.000  61.526  504.000
coldlaunch.navigationInteractive  737.400  756.500  625.000  855.000  76.970  855.000
coldlaunch.visuallyLoaded         737.400  756.500  625.000  855.000  76.970  855.000
coldlaunch.contentInteractive     737.700  757.500  625.000  855.000  76.953  855.000
coldlaunch.fullyLoaded            888.700  896.000  795.000  970.000  53.887  970.000
coldlaunch.pss                    14.500   14.500   14.400   14.600   0.045   14.600 
coldlaunch.uss                    10.190   10.200   10.000   10.300   0.070   10.300 
coldlaunch.rss                    28.850   28.850   28.700   29.000   0.081   29.000 
```

```
After                            Mean     Median   Min      Max       StdDev  p95     
--------------------------------  -------  -------  -------  --------  ------  --------
coldlaunch.navigationLoaded       337.400  335.000  306.000  390.000   22.822  390.000 
coldlaunch.navigationInteractive  792.200  810.000  626.000  941.000   96.714  941.000 
coldlaunch.visuallyLoaded         793.000  810.000  626.000  942.000   96.227  942.000 
coldlaunch.contentInteractive     793.200  810.000  627.000  942.000   95.981  942.000 
coldlaunch.fullyLoaded            928.200  930.000  797.000  1091.000  91.448  1091.000
coldlaunch.rss                    28.760   28.800   28.600   28.800    0.066   28.800  
coldlaunch.uss                    10.080   10.100   9.900    10.200    0.087   10.200  
coldlaunch.pss                    14.450   14.500   14.300   14.500    0.067   14.500  
```

**Comment by zbraniecki** [comment]
r+

**Comment by stasm** [comment]
The numbers for FM Radio are not faster. Could you help me verify that this doesn't regress the perf in other apps, please?

**Pull request merged**
