### PR TITLE
Fixed square boxes in Microsoft browsers, including Edge.

### PR DESCRIPTION
**Pull request by poscar**
The FSI and PDI characters are displayed as square boxes in Microsoft browsers (see attached screenshot). This pull request fixes that issue.

I know it removes the FSI and PDI markers, but I believe disabling them is better than incorrectly displaying square boxes for any replaced strings that result in the subPlaceable function being called.

screen-shot-2016-03-22-at-8 05 49-pm

### CODE REVIEW

**Comment by zbraniecki** [comment]
I think that we should make it configurable if anything. Removing functionality that is used by products relying on l20n (that don't target Edge), is not a solution.

**Comment by poscar** [comment]
@zbraniecki What would be the right way to make this configurable?  Separate dist?

**Comment by stasm** [comment]
@poscar Can you please create your PR against master rather than 3.x?

**Comment by stasm** [comment]
We could use `<bdi>` instead of the Unicode marks.

**Comment by poscar** [comment]
@stasm, Ok. I'll try out <bdi> and make the pull request against master.

**Pull request closed without merging**
