### PR TITLE
Remove support for .innerHTML

### PR DESCRIPTION
**Pull request by stasm**
@zbraniecki r?

### CODE REVIEW

**Comment by zbraniecki** [comment]
r+ unless it affects l10n.js apps at build time.

**Comment by stasm** [comment]
Great point, I double checked and there is indeed one string that might be affected: https://github.com/mozilla-b2g/gaia/blob/f7762c4b56b881b1569671973d02754032ed4685/apps/ftu/locales/ftu.en-US.properties#L203

It should be enough to just remove `.innerHTML` from it in the Gaia pr. I'm testing right now, though, and it seems to work either way.

**Comment by stasm** [comment]
OK,so what I think I happens is:  build/l10n/l20n.js clears the fxa-upsell node during the pretranslation, but FTU still has its own logic which uses `setAttributes`and localizes the node with the runtime l10n.js, which supports innerHTML.

**Comment by stasm** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1191163 to remove that `innerHTML` from FTU before I merge this.

**Pull request merged**
